### ISSUE TITLE
Floats and Doubles allowed in but not out

### ISSUE THREAD

**Issue by decapo01** [tchoutri/pg-entity#23]
I'm not sure if this is an issue with this library or the postgresql-simple library, but if there is a field in postgres with the `decimal` or `numeric` type, inserting floats and doubles are allowed however when trying to retrieve the record an error will occur
```
Incompatible {errSQLType = "numeric", errSQLTableOid = Just (Oid 16400), errSQLField = "yield_strength", errHaskellType = "Double", errMessage = "types incompatible"}
```

**Comment by tchoutri** [comment]
@decapo01 Hi! 

From what I can see in the postgresql-simple [source code](https://github.com/haskellari/postgresql-simple/blob/6cabb13959310f32a15285f8e41c2d053403d687/src/Database/PostgreSQL/Simple/FromField.hs#L152), `numeric` needs to be declared as a `Ratio Integer` or `Scientific`, whereas `Double` only accepts `float40`, `float80`, `int20` and `int40` (and `Float` only accepts `flaot20` and `float40`).

Since you're expecting a `Float` from your `numeric`, I have no doubt it will clash. :)

**Comment by decapo01** [comment]
> @decapo01 Hi!
> 
> From what I can see in the postgresql-simple [source code](https://github.com/haskellari/postgresql-simple/blob/6cabb13959310f32a15285f8e41c2d053403d687/src/Database/PostgreSQL/Simple/FromField.hs#L152), `numeric` needs to be declared as a `Ratio Integer` or `Scientific`, whereas `Double` only accepts `float40`, `float80`, `int20` and `int40` (and `Float` only accepts `flaot20` and `float40`).
> 
> Since you're expecting a `Float` from your `numeric`, I have no doubt it will clash. :)

But shouldn't this fail on insertion then?  If it's a postgresql-simple issue then it would probably be better to open it there.

**Comment by tchoutri** [comment]
@decapo01 See that's the problem: on insertion, your Double or Float (as encoded in the SQL via [floatDec](https://hackage.haskell.org/package/bytestring-0.11.2.0/docs/Data-ByteString-Builder.html#v:floatDec)) will match with `numeric`, due to type inference of the literals.

If you look at the documentation for [`NUMERIC`](https://www.postgresql.org/docs/9.1/datatype-numeric.html):

> The type numeric can store numbers with a very large number of digits and perform calculations exactly.

As such, while it can accept numbers like `Doubles` or `Floats` from the Haskell world, we can't be certain that these values will fit in our `Floats` and `Doubles`, so we need to make sure there will always be enough room, hence the use of `Scientific`.

I don't think this is an issue in terms of "how it is supposed to work" but you would be right to submit a patch to postgresql-simple regarding documentation. :)
